apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0982cc04fc018c394
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
--- 
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-static-claim
    persistentVolumeClaim:
      claimName: ebs-static-claim