apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-ebs
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: expense-ebs
  resources:
    requests:
      storage: 4Gi