apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: frontend
  namespace: expense
  labels:
    tier: web 
    app: frontend
    project: expense
spec: 
  replicas: 1
  selector:
    matchLabels:
      tier: web 
      app: frontend
      project: expense
  template: 
    metadata: 
      labels: 
       tier: web 
       app: frontend
       project: expense
    spec: 
      containers: 
      - name: frontend
        image: joindevops/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web 
    project: expense
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80
    targetPort: 80