apiVersion: v1
kind: Pod
metadata: 
  name: environments 
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
    - name: course
      value: kubernetes
    - name: trainer
      value: "divya"