apiVersion: apps/v1 
kind: ReplicaSet
metadata: 
  name: rs
  labels:
    tier: web 
spec: 
  replicas: 3 
  selector:
    matchLabels:
      tier: web 
  template: 
    metadata: 
      labels: 
        tier: web 
    spec: 
      containers: 
      - name: nginx
        image: nginx:stable-perl

